apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: restaurant-system
  labels:
    app: pgbouncer
spec:
  replicas: 2                      # stateless — scale horizontally
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
      containers:
        - name: pgbouncer
          image: bitnami/pgbouncer:1.22.1
          ports:
            - containerPort: 6432
          env:
            - name: POSTGRESQL_HOST
              value: postgres
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_DATABASE
              value: restaurant_booking
            - name: POSTGRESQL_USERNAME
              value: admin
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurant-secrets
                  key: POSTGRES_PASSWORD
            - name: PGBOUNCER_POOL_MODE
              value: transaction
            - name: PGBOUNCER_MAX_CLIENT_CONN
              value: "100"
            - name: PGBOUNCER_DEFAULT_POOL_SIZE
              value: "25"
            - name: PGBOUNCER_SERVER_IDLE_TIMEOUT
              value: "600"
            - name: PGBOUNCER_IGNORE_STARTUP_PARAMETERS
              value: extra_float_digits
          livenessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 6432
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: restaurant-system
spec:
  type: ClusterIP
  selector:
    app: pgbouncer
  ports:
    - port: 6432
      targetPort: 6432
