apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.apiGateway.env.JWT_SECRET | default "" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | default "" | b64enc | quote }}
  MONGO_PASSWORD: {{ .Values.mongodb.auth.password | default "" | b64enc | quote }}
  OPENAI_API_KEY: {{ .Values.aiService.env.OPENAI_API_KEY | default "" | b64enc | quote }}
